image: docker:latest

stages:
  - build
  - release

services:
  - docker:dind

variables:
  SCRAPER_ORCHESTRATION_IMAGE_NAME: registry.gitlab.com/cado82/football-stats-api/scraper/orchestration
  SCRAPER_LEAGUE_SUMMARY_IMAGE_NAME: registry.gitlab.com/cado82/football-stats-api/scraper/leaguesummary
  WEB_APP_IMAGE_NAME: registry.gitlab.com/cado82/football-stats-api/web/app
  NGINX_IMAGE_NAME: registry.gitlab.com/cado82/football-stats-api/nginx
  API_APP_IMAGE_NAME: registry.gitlab.com/cado82/football-stats-api/api/app
  DB_MIGRATIONS_IMAGE_NAME: registry.gitlab.com/cado82/football-stats-api/db/migrations

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -f ./src/FootballStatsApi.Scraper.Orchestration/Dockerfile -t $SCRAPER_ORCHESTRATION_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA ./src
    - docker build --pull -f ./src/FootballStatsApi.Scraper.LeagueSummary/Dockerfile -t $SCRAPER_LEAGUE_SUMMARY_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA ./src
    - docker build --pull -f ./src/FootballStatsApi.Web/app/Dockerfile -t $WEB_APP_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA ./src
    - docker build --pull -f ./src/nginx/Dockerfile -t $NGINX_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA ./src
    - docker build --pull -f ./src/FootballStatsApi/app/Dockerfile -t $API_APP_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA ./src
    - docker build --pull -f ./src/FootballStatsApi.Database/Dockerfile -t $DB_MIGRATIONS_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA ./src
    - docker push $SCRAPER_ORCHESTRATION_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - docker push $SCRAPER_LEAGUE_SUMMARY_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - docker push $WEB_APP_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - docker push $NGINX_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - docker push $API_APP_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - docker push $DB_MIGRATIONS_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA

release:
  stage: release
  script:
    - docker pull $SCRAPER_ORCHESTRATION_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - docker pull $SCRAPER_LEAGUE_SUMMARY_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - docker pull $WEB_APP_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - docker pull $NGINX_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - docker pull $API_APP_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - docker pull $DB_MIGRATIONS_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - docker tag $SCRAPER_ORCHESTRATION_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA $SCRAPER_ORCHESTRATION_IMAGE_NAME:latest
    - docker tag $SCRAPER_LEAGUE_SUMMARY_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA $SCRAPER_LEAGUE_SUMMARY_IMAGE_NAME:latest
    - docker tag $WEB_APP_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA $WEB_APP_IMAGE_NAME:latest
    - docker tag $NGINX_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA $NGINX_IMAGE_NAME:latest
    - docker tag $API_APP_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA $API_APP_IMAGE_NAME:latest
    - docker tag $DB_MIGRATIONS_IMAGE_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA $DB_MIGRATIONS_IMAGE_NAME:latest
    - docker push $SCRAPER_ORCHESTRATION_IMAGE_NAME:latest
    - docker push $SCRAPER_LEAGUE_SUMMARY_IMAGE_NAME:latest
    - docker push $WEB_APP_IMAGE_NAME:latest
    - docker push $NGINX_IMAGE_NAME:latest
    - docker push $API_APP_IMAGE_NAME:latest
    - docker push $DB_MIGRATIONS_IMAGE_NAME:latest
  only:
    - master