version: '3'
services:
  api-app: # fsa-api-1
    image: registry.gitlab.com/cado82/football-stats-api/api/app:latest
    restart: "always"
    expose:
      - 5000
    environment:
      ConnectionStrings__Football:
      ASPNETCORE_ENVIRONMENT: Production
  api-nginx: # fsa-api-1
    image: registry.gitlab.com/cado82/football-stats-api/api/nginx:latest
    restart: "always"
    ports:
      - "80:80"
