version: '3'
services:
  web-app: # fsa-web-1
    image: registry.gitlab.com/cado82/football-stats-api/web/app:latest
    restart: "always"
    expose:
      - 5000
    environment:
      ConnectionStrings__Football:
      ASPNETCORE_ENVIRONMENT: Production
      TokenSigningCert: /etc/ssl/certs/FootballStatsApiCert.p12
      TokenSigningCertSecret:
  web-nginx: # fsa-web-1
    image: registry.gitlab.com/cado82/football-stats-api/web/nginx:latest
    restart: "always"
    ports:
      - "80:80"