version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fsa-rabbitmq
    restart: always
    logging:
      driver: none
    expose:
      - 5672
    ports:
      - "8080:15672"
  scraper-orchestration:
    depends_on:
      - db
      - db-migrations
      - rabbitmq
    build:
      context: .
      dockerfile: FootballStatsApi.Scraper.Orchestration/Dockerfile
    image: fsa-orchestration:latest
    environment:
      ConnectionStrings__AMQP: amqp://guest:guest@rabbitmq
      ConnectionStrings__Football: Server=db;User Id=postgres;Password=admin;Database=football;
  scraper:
    depends_on:
      - db
      - db-migrations
      - rabbitmq
    build:
      context: .
      dockerfile: FootballStatsApi.Scraper.LeagueSummary/Dockerfile
    image: fsa-scraper:latest
    security_opt: 
      - seccomp:unconfined
    environment:
      ConnectionStrings__AMQP: amqp://guest:guest@rabbitmq
      ConnectionStrings__Football: Server=db;User Id=postgres;Password=admin;Database=football;
  web:
    depends_on:
      - db
      - db-migrations
    build:
      context: .
      dockerfile: FootballStatsApi.Web/app/Dockerfile
    image: fsa-web:latest
    ports:
      - "8070:5000"
    environment:
      ConnectionStrings__Football: Server=db;User Id=postgres;Password=admin;Database=football;
      ASPNETCORE_ENVIRONMENT: Development
  api:
    depends_on:
      - db
      - db-migrations
    build:
      context: .
      dockerfile: FootballStatsApi/app/Dockerfile
    image: fsa-api:latest
    ports:
      - "8060:5000"
    environment:
      ConnectionStrings__Football: Server=db;User Id=postgres;Password=admin;Database=football;
      ASPNETCORE_ENVIRONMENT: Development
  db:
    image: postgres:11
    container_name: fsa-db
    logging:
      driver: none
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: football
    expose:
      - "5432"
    ports:
      - "8090:5432"
    command:
      - "postgres"
      - "-c"
      - "max_connections=300"
  db-migrations:
    depends_on:
      - db
    container_name: fsa-dbmigrations
    build:
      context: .
      dockerfile: FootballStatsApi.Database/Dockerfile
    image: fsa-dbmigrations:latest
    environment:
      ConnectionStrings__FootballAdmin: Server=db;User Id=postgres;Password=admin;Database=football;