version: '3'
services:
  chrome:
    image: registry.gitlab.com/cado82/football-stats-api/scraper/chrome:latest
    security_opt: 
      - seccomp:unconfined
    restart: "always"
    expose:
      - 9222
  scraper:
    image: registry.gitlab.com/cado82/football-stats-api/scraper/leaguesummary:latest
    restart: "always"
    environment:
      ConnectionStrings__AMQP:
      ConnectionStrings__Football:
      ChromeRemoteDebuggingHost: chrome
      ChromeRemoteDebuggingPort: 9222
      DOTNET_ENVIRONMENT: Production